config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  get 'posts/index'

  get 'feed' => 'articles#feed'

  resources :articles do
  	resources :comments
  end

  get 'welcome/index'
  root 'welcome#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new #in case of guest
    if user.role_id == 1
      can :manage, :all 
    else
      can :read, :all 
    end 
  end
end

app/models/admin_ability.rb
class AdminAbility < ActiveRecord::Base
	include CanCan::Ability
	def initialize(user)
		# if user && user.admin?
		can :access, :rails_admin
		can :manage, :all
		# end
	end
end

app/models/article.rb
class Article < ActiveRecord::Base
	extend FriendlyId
	friendly_id :title, use: :slugged
	has_many :comments, dependent: :destroy
	validates :title, presence: true,
						length: {minimum: 5}
	validates :text, presence: true	

	# include Bootsy::Container
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/page.rb
class Page < ActiveRecord::Base
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
#  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_and_belongs_to_many :roles, :join_table => :users_roles

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/:style/missing_profile.png"
  validates_attachment_content_type :avatar, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  # User::Roles
  # The available Roles
  # Roles = [:admin, :default]

  # def is?(requested_role)
  # 	self.role == requested_role.to_s
  # end

  # def admin?
  #   self.role.name == "Admin"
  # end

  # def default?
  #   self.role.name == "Default"
  # end
  # 
  # def has_role?(role_sym)
  #   roles.any? { |r| r.name.unserscore.to_sym == role_sym }
  # end

  # In the following code you can change the way rails admin declares field on the backend.
  # rails_admin do
  #   edit do
  #     field :email
  #     field :role

  #   end
  # end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
	# rescue_from CanCan::AccessDenied do |exception|
	# 	redirect_to main_app.root_path, :alert => exception.message
	# end

 #  def current_user
	# 	if user_signed_in?
	# 		return @user.email
	# 	else
	# 		return "Guest"
	# 	end
	# end

	def configure_permitted_parameters
		devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password) }
		devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :current_password, :is_female, :date_of_birth, :avatar) }
	end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	# before_filter :signed_in_user, :only=> [:edit, :update, :new]
	before_action :authenticate_user!, :except=> [:index, :show] #Prevets the non signed in user from creating a new blog post
	def index
		@articles = Article.all.paginate(page: params[:page], per_page: 5)
	end

	def show
		# @article = Article.find(params[:id])
		@article = Article.friendly.find(params[:id])

		if request.path != article_path(@article)
			redirect_to @article, status: :moved_permanently
		end
	end

	def new
		@article = Article.new
	end

	def edit
		@article = Article.find(params[:id])
	end

	
	def create
		# render plain: params[:article].inspect
		@article = Article.new(article_params)
		
		if @article.save
			redirect_to @article
		else
			render 'new'
		end
	end

	def update
		@article = Article.find(params[:id])

		if @article.update(article_params)
			redirect_to @article
		else	
			render 'edit'
		end
	end

	def destroy
		@article = Article.find(params[:id])
		@article.destroy

		redirect_to article_path
	end

	def feed
		@articles = Article.all
		respond_to do |format|
			format.rss {render :layout=> false}
		end	
	end
	
	private
	def article_params
		params.require(:article).permit(:title, :text, :bootsy_image_gallery_id)
	end

	def set_article
		@article - Article.friendly.find(params[:id])
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@article = Article.find(params[:article_id])
		@comment = @article.comments.create(comments_params)
		# redirect_to article_path(@article)
		respond_to do |format|
			format.html {redirect_to article_path(@article)}
			format.js
		end
	end

	def destroy
		@article = Article.find(params[:article_id])
		@comment = @article.comments.find(params[:id])
		@comment.destroy
		redirect_to article_path(@article)
	end


	private
	def comments_params
		params.require(:comment).permit(:commenter, :body)
	end		

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
	load_and_authorize_resource
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def user_params
		params.require(:user).permit(:email, :role)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def avatar_url(user)
		gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
		"http://gravatar.com/avatar/#{gravatar_id}.png"
	end

	def is_active?(link_path)
		current_page?(link_path) ? "active" : ""
	end
	
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper

	# def article_nav
	# 	@pages.each do |page|
	# 		<a href=/"/articles/{{page.id}}/">page.title </a>
	# 	end
	# end	
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article, :validate => true do |f| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.cktext_area :text%>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>
<% if user_signed_in? %>
	<%= link_to 'New Article', new_article_path %>
<% end -%>

<!-- Try making listing of article beautiful -->
<% @articles.each do |article| %>
	<div class="row clearfix">
		<div class="col-md-12 column">
			<div class="row clearfix">
				<div class="col-md-8 column">
					<h3 class="text-center">
						<%= article.title %>
					</h3>
				</div>
				<div class="col-md-4 column">
					<img class="img-circle" alt="140x140" src="http://lorempixel.com/140/140/" />
				</div>
			</div>
			<p>
				<%= article.text %>
			</p>
		</div>
		<div>
		<ul class="nav nav-pills">
			<li>
				<!-- <span class="badge pull-right"></span> -->
				<span class="glyphicon glyphicon-pencil" aria-hidden="true">
				<%= link_to 'Show', article_path(article) %>
			
				 
			</li>
			<li>
				<span class="badge pull-right"></span>
				<span class="glyphicon glyphicon-pencil" aria-hidden="true">
				<%= link_to 'Edit', edit_article_path(article) %>
			</li>
			<li>				
  				<span class="glyphicon glyphicon-pencil" aria-hidden="true">
				<%= link_to 'Destroy', article_path(	article),
					method: :delete,
					data: {confirm: 'Are you sure?'} %>
				
			</li>
		</ul>
		</div>
	</div>
<% end -%>
<div align="center">
<%= will_paginate @articles, renderer: BootstrapPagination::Rails %>
</div>

app/views/articles/new.html.erb
<h1>New Articles</h1>
<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p>
<strong>Title:</strong>
<%= @article.title %>
</p>

<p>
<strong>Text:</strong>
<%= raw(@article.text) %>	
</p>


<h2>Comments</h2>
<%= render @article.comments %>
<div id="comment"></div>
<div>
	<h2>Add a comment:</h2>
	<%= render 'comments/form' %>
</div>



<%= link_to 'Edit', edit_article_path(@article) %>
<%= link_to 'Back', articles_path %>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>


<p>
	<%= link_to 'Destroy Comment', [comment.article, comment],
			method: :delete,
			data: {confirm: 'Are you sure?'} %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build], :remote => true) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/comments/create.js.erb
$('#comment').append('<%= escape_javascript(render @comment) %>');
$('#comment_body').val('')
$('#comment_commenter').val('')

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/index.html.haml
%p
	%h1 Hello
	-if user_signed_in?
		=image_tag avatar_url(current_user)
		%li{:class=> "round-image-50" } 
			=image_tag current_user.avatar.url(:thumb)
		%br
		=current_user.email

	-else
		Guest

	=link_to 'My Blog', controller: 'articles' 